### ISSUE TITLE
Unable to install Slepc with Spack

### ISSUE THREAD

**Issue by babouFomb** [slepc/slepc#1]
Hello,
I try to use Slepc in my project. I use Spack to install my third-parties libraries (Petsc, Slepc). However, I have the following problem :

> ==> Installing slepc-3.20.0-giejvjpp3erlndotfg26gk4etkrqf5lb [68/83]
==> No binary for slepc-3.20.0-giejvjpp3erlndotfg26gk4etkrqf5lb found: installing from source
==> Using cached archive: spack/var/spack/cache/_source-cache/archive/78/780c50260a9bc9b72776cb920774800c73832370938f1d48c2ea5c66d31b7380.tar.gz
==> No patches needed for slepc
==> slepc: Executing phase: 'install'
==> Error: ProcessError: Command exited with status 1:
    'spack/opt/spack/linux-ubuntu22.04-skylake/gcc-11.4.0/python-3.11.6-zsx4uf6zzi6qk7aq5npl4mqodrlqwhdw/bin/python3.11' 'configure' '--prefix=spack/opt/spack/linux-ubuntu22.04-skylake/gcc-11.4.0/slepc-3.20.0-giejvjpp3erlndotfg26gk4etkrqf5lb' '--with-arpack-include=spack/opt/spack/linux-ubuntu22.04-skylake/gcc-11.4.0/arpack-ng-3.9.0-jamzckldpepdd6kuwbouyfjh7tnuve3s/include' '--with-arpack-lib=spack/opt/spack/linux-ubuntu22.04-skylake/gcc-11.4.0/arpack-ng-3.9.0-jamzckldpepdd6kuwbouyfjh7tnuve3s/lib/libparpack.so spack/opt/spack/linux-ubuntu22.04-skylake/gcc-11.4.0/arpack-ng-3.9.0-jamzckldpepdd6kuwbouyfjh7tnuve3s/lib/libarpack.so'
See build log for details:
  /tmp/$USER/spack-stage/spack-stage-slepc-3.20.0-giejvjpp3erlndotfg26gk4etkrqf5lb/spack-build-out.txt

The log file is : 
[configure.log](https://github.com/user-attachments/files/15883331/configure.log)

My Spack specs for Petsc and Slepc are in this file : 
[speck.md](https://github.com/user-attachments/files/15883394/speck.md)

Build system : Ubuntu 22.04.4, Gcc/G++ 11.4.0
Spack version 0.21.0
Slepc 3.20.0

How can I resolve this problem.

Thank you.

**Comment by joseeroman** [comment]
See discussion at https://github.com/spack/spack/issues/44758
